### ISSUE TITLE
Missing SSL support in python2 breaks the script

### ISSUE THREAD

**Issue by mikaelgoldmann** [Kattis/kattis-cli#10]
Easiest fix is probably to make it python3 only. With python2, the user needs to go to some effort to make it work. At least on Mac and Ubuntu 14.04 it doesn't work out of the box with python2.

Workarounds:
- Depending on your setup, this might not be a problem for you
- You can try running the script using python3

**Comment by mikaelgoldmann** [comment]
This may not be SNI specifically, but the openssl libs on Mac as well as Ubuntu 14.04 at least have issues.

**Comment by austrin** [comment]
@mikaelgoldmann close this?

**Comment by mikaelgoldmann** [comment]
Oh, right, doesn't auto close of course.
