### ISSUE TITLE
open_submission(submit_response, cfg) function is broken

### ISSUE THREAD

**Issue by sikfeng** [Kattis/kattis-cli#24]
PROBLEM:
Firstly, the function executes `submissions_url = get_url(cfg, 'submissionsurl', 'submissions')`, which is an error as `.kattisrc` contains `submissionurl`, not `submissionsurl`.

Secondly, the url is for accessing submissions is `https://open.kattis.com/submissions/`, not `https://open.kattis.com/submit/`. 

FIX:
I added the line `opensubmission: https://open.kattis.com/submissions` to the end of`.kattisrc` and also changed `submissions_url = get_url(cfg, 'submissionsurl', 'submissions')` on line 170 to `submissions_url = get_url(cfg, 'opensubmission', 'submissions')`

This would require the modification of the file at `https://open.kattis.com/download/kattisrc`

**Comment by simonlindholm** [comment]
Fixed on the Kattis side; will go out in the next deploy. Thanks for reporting!
