### ISSUE TITLE
Hello Kattis Devs:

### ISSUE THREAD

**Issue by MarkWardell** [Kattis/kattis-cli#25]
I am trying to use PostMan.exe to study and replicate the results from submit.py line 97
[requests.post(login_url, data=login_args, headers=_HEADERS)]

I am new to Postman and am not having any luck if any of you developers could instruct me in this it would be appreciated.

Kind Regards,
Mark

**Comment by pehrsoderman** [comment]
I have no experience wit PostMan (and this answer is about a year late), but I hope you figured it out.
